/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppRoutineCreateRouteRouteImport } from './routes/_app._routine-create/route'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppRoutinesRouteImport } from './routes/_app.routines'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRoutineCreateRoutinesNewRouteImport } from './routes/_app._routine-create/routines_.new'
import { Route as AppRoutineCreateRoutinesNewExercisesRouteImport } from './routes/_app._routine-create/routines_.new_.exercises'
import { Route as AppRoutineCreateRoutinesNewExercisesExerciseIdRouteImport } from './routes/_app._routine-create/routines_.new_.exercises_.$exerciseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoutineCreateRouteRoute = AppRoutineCreateRouteRouteImport.update({
  id: '/_routine-create',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutinesRoute = AppRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutineCreateRoutinesNewRoute =
  AppRoutineCreateRoutinesNewRouteImport.update({
    id: '/routines_/new',
    path: '/routines/new',
    getParentRoute: () => AppRoutineCreateRouteRoute,
  } as any)
const AppRoutineCreateRoutinesNewExercisesRoute =
  AppRoutineCreateRoutinesNewExercisesRouteImport.update({
    id: '/routines_/new_/exercises',
    path: '/routines/new/exercises',
    getParentRoute: () => AppRoutineCreateRouteRoute,
  } as any)
const AppRoutineCreateRoutinesNewExercisesExerciseIdRoute =
  AppRoutineCreateRoutinesNewExercisesExerciseIdRouteImport.update({
    id: '/routines_/new_/exercises_/$exerciseId',
    path: '/routines/new/exercises/$exerciseId',
    getParentRoute: () => AppRoutineCreateRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/routines': typeof AppRoutinesRoute
  '/settings': typeof AppSettingsRoute
  '/routines/new': typeof AppRoutineCreateRoutinesNewRoute
  '/routines/new/exercises': typeof AppRoutineCreateRoutinesNewExercisesRoute
  '/routines/new/exercises/$exerciseId': typeof AppRoutineCreateRoutinesNewExercisesExerciseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/routines': typeof AppRoutinesRoute
  '/settings': typeof AppSettingsRoute
  '/routines/new': typeof AppRoutineCreateRoutinesNewRoute
  '/routines/new/exercises': typeof AppRoutineCreateRoutinesNewExercisesRoute
  '/routines/new/exercises/$exerciseId': typeof AppRoutineCreateRoutinesNewExercisesExerciseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/_routine-create': typeof AppRoutineCreateRouteRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/routines': typeof AppRoutinesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/_routine-create/routines_/new': typeof AppRoutineCreateRoutinesNewRoute
  '/_app/_routine-create/routines_/new_/exercises': typeof AppRoutineCreateRoutinesNewExercisesRoute
  '/_app/_routine-create/routines_/new_/exercises_/$exerciseId': typeof AppRoutineCreateRoutinesNewExercisesExerciseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/history'
    | '/routines'
    | '/settings'
    | '/routines/new'
    | '/routines/new/exercises'
    | '/routines/new/exercises/$exerciseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/routines'
    | '/settings'
    | '/routines/new'
    | '/routines/new/exercises'
    | '/routines/new/exercises/$exerciseId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/_routine-create'
    | '/_app/dashboard'
    | '/_app/history'
    | '/_app/routines'
    | '/_app/settings'
    | '/_app/_routine-create/routines_/new'
    | '/_app/_routine-create/routines_/new_/exercises'
    | '/_app/_routine-create/routines_/new_/exercises_/$exerciseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_routine-create': {
      id: '/_app/_routine-create'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRoutineCreateRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routines': {
      id: '/_app/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof AppRoutinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_routine-create/routines_/new': {
      id: '/_app/_routine-create/routines_/new'
      path: '/routines/new'
      fullPath: '/routines/new'
      preLoaderRoute: typeof AppRoutineCreateRoutinesNewRouteImport
      parentRoute: typeof AppRoutineCreateRouteRoute
    }
    '/_app/_routine-create/routines_/new_/exercises': {
      id: '/_app/_routine-create/routines_/new_/exercises'
      path: '/routines/new/exercises'
      fullPath: '/routines/new/exercises'
      preLoaderRoute: typeof AppRoutineCreateRoutinesNewExercisesRouteImport
      parentRoute: typeof AppRoutineCreateRouteRoute
    }
    '/_app/_routine-create/routines_/new_/exercises_/$exerciseId': {
      id: '/_app/_routine-create/routines_/new_/exercises_/$exerciseId'
      path: '/routines/new/exercises/$exerciseId'
      fullPath: '/routines/new/exercises/$exerciseId'
      preLoaderRoute: typeof AppRoutineCreateRoutinesNewExercisesExerciseIdRouteImport
      parentRoute: typeof AppRoutineCreateRouteRoute
    }
  }
}

interface AppRoutineCreateRouteRouteChildren {
  AppRoutineCreateRoutinesNewRoute: typeof AppRoutineCreateRoutinesNewRoute
  AppRoutineCreateRoutinesNewExercisesRoute: typeof AppRoutineCreateRoutinesNewExercisesRoute
  AppRoutineCreateRoutinesNewExercisesExerciseIdRoute: typeof AppRoutineCreateRoutinesNewExercisesExerciseIdRoute
}

const AppRoutineCreateRouteRouteChildren: AppRoutineCreateRouteRouteChildren = {
  AppRoutineCreateRoutinesNewRoute: AppRoutineCreateRoutinesNewRoute,
  AppRoutineCreateRoutinesNewExercisesRoute:
    AppRoutineCreateRoutinesNewExercisesRoute,
  AppRoutineCreateRoutinesNewExercisesExerciseIdRoute:
    AppRoutineCreateRoutinesNewExercisesExerciseIdRoute,
}

const AppRoutineCreateRouteRouteWithChildren =
  AppRoutineCreateRouteRoute._addFileChildren(
    AppRoutineCreateRouteRouteChildren,
  )

interface AppRouteChildren {
  AppRoutineCreateRouteRoute: typeof AppRoutineCreateRouteRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppRoutinesRoute: typeof AppRoutinesRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppRoutineCreateRouteRoute: AppRoutineCreateRouteRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppRoutinesRoute: AppRoutinesRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
